[build]
  publish = "public"
  command = "yarn run build"
[build.environment]
  YARN_VERSION = "1.7.0"

[[redirects]]
  from = "/ns-chat"
  to = "https://www.meetingbird.com/h/rajk"
  status = 200

[[redirects]]
  from = "/chat"
  to = "https://calendly.com/kunksed/chat"
  status = 302
  
[[redirects]]
  from = "/team"
  to = "https://calendly.com/kunksed/stoateam"
  status = 302
  
[[redirects]]
  from = "/stoa"
  to = " https://calendly.com/kunksed/stoa"
  status = 302
  
  [[redirects]]
  from = "/wa"
  to = "http://wa.me/919673374334"
  status = 302
  
  [[redirects]]
  from = "/ig"
  to = "http://instagram.com/kunksed"
  status = 302
  
  [[redirects]]
  from = "/zoom"
  to = "https://zoom.us/j/9138548093?pwd=TmgvdEIzMnFLWFZMYTg0MHdydmUrdz09"
  status = 302
  
  [[redirects]]
  from = "/zoomlink"
  to = "https://us02web.zoom.us/j/81849919671"
  status = 302
  
    [[redirects]]
  from = "/boomlink"
  to = "https://us04web.zoom.us/j/71662669491?pwd=VEgvQ25IYlBUMnR0VnpCWGhjY285dz09"
  status = 302

  [[redirects]]
  from = "/panelists"
  to = "https://us02web.zoom.us/j/81849919671"
  status = 302
